# Basic Information
title: Mingjie Zhang
position: Statistics
affiliation: USTC,SGY
email: mingjiezhang415411@gmail.com

# Links
github_link: https://github.com/MingjieZhangQWQ
linkedin: https://www.linkedin.com/in/mingjie-zhang-136bb02b2/

# Images
# avatar: ./assets/img/avatar.jpg
# favicon: ./assets/img/favicon.png

# Theme Settings
remote_theme: yaoyao-liu/minimal-light
